// THIS FILE IS AUTO-GENERATED by astro-pagescms
// Source: .pages.yml — do not edit manually, changes will be overwritten on next build

import { file, glob } from 'astro/loaders';
import { z } from 'astro/zod';
import type { SchemaContext } from 'astro:content';
import { defineCollection } from 'astro:content';

// Shared component schemas
const seoSchema = (image: SchemaContext['image']) =>
  z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  image: image().or(z.string()).optional(),
}).optional();
const image_with_altSchema = (image: SchemaContext['image']) =>
  z.object({
  src: image().or(z.string()).optional(),
  alt: z.string().optional(),
}).optional();

// Collections
const pages = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/pages" }),
  schema: ({ image }) =>
    z.object({
  uuid: z.string().uuid().optional(),
  title: z.string().optional(),
  description: z.string().optional(),
  slug: z.string().optional(),
  seo: seoSchema(image).optional(),
  sections: z.array(
z.discriminatedUnion("type", [
z.object({
  type: z.literal("halftoneHeroBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  subtitle: z.string().optional(),
  minHeight: z.string().optional(),
}),
z.object({
  type: z.literal("imageHeroBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  subtitle: z.string().optional(),
  image: image().or(z.string()),
  imageAlt: z.string().optional(),
  minHeight: z.string().optional(),
  colorScheme: z.enum(["light", "dark"]).optional(),
}),
z.object({
  type: z.literal("headingBlock"),
  heading: z.string().optional(),
  subtitle: z.string().optional(),
  id: z.string().optional(),
  pt: z.enum(["none", "sm", "md", "lg", "xl", "2xl"]).optional(),
  pb: z.enum(["none", "sm", "md", "lg", "xl", "2xl"]).optional(),
}),
z.object({
  type: z.literal("videoHeroBlock"),
  id: z.string().optional(),
  src: z.string(),
  poster: image().or(z.string()).optional(),
}),
z.object({
  type: z.literal("contactBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  subtitle: z.string().optional(),
}),
z.object({
  type: z.literal("leadBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  body: z.string().optional(),
}),
z.object({
  type: z.literal("textBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  body: z.string().optional(),
}),
z.object({
  type: z.literal("clientLogosBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  subtitle: z.string().optional(),
}),
z.object({
  type: z.literal("serviceCardsBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  subtitle: z.string().optional(),
}),
z.object({
  type: z.literal("caseStudyGridBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  subtitle: z.string().optional(),
  order: z.array(z.string()).default([]),
}),
z.object({
  type: z.literal("galleryBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  images: z.array(z.object({
  src: image().or(z.string()).optional(),
  alt: z.string().optional(),
})).default([]),
}),
z.object({
  type: z.literal("mediaTextBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  body: z.string().optional(),
  image: z.object({
  src: image().or(z.string()).optional(),
  alt: z.string().optional(),
}).optional(),
  mediaSide: z.enum(["left", "right"]).optional(),
  padding: z.enum(["none", "sm", "md", "lg", "xl", "2xl"]).optional(),
  fixedRatio: z.string().optional(),
  cta: z.object({
  label: z.string().optional(),
  href: z.string().optional(),
}).optional(),
}),
z.object({
  type: z.literal("tileGridBlock"),
  id: z.string().optional(),
  columns: z.enum(["2", "3"]).optional(),
  items: z.array(z.object({
  title: z.string().optional(),
  image: image().or(z.string()).optional(),
  imageAlt: z.string().optional(),
  href: z.string().optional(),
  cta: z.string().optional(),
})).default([]),
}),
z.object({
  type: z.literal("textGridBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  subtitle: z.string().optional(),
  items: z.array(z.object({
  title: z.string().optional(),
  body: z.string().optional(),
})).default([]),
}),
z.object({
  type: z.literal("mediaBlock"),
  id: z.string().optional(),
  mediaType: z.enum(["image", "video"]).optional(),
  image: image().or(z.string()).optional(),
  imageAlt: z.string().optional(),
  youtubeUrl: z.string().optional(),
  caption: z.string().optional(),
  width: z.enum(["full", "wide", "default", "narrow"]).optional(),
  padding: z.enum(["none", "sm", "md", "lg", "xl", "2xl"]).optional(),
}),
z.object({
  type: z.literal("blogPostsCarouselBlock"),
  id: z.string().optional(),
  heading: z.string().optional(),
  subtitle: z.string().optional(),
}),
])
).default([]),
}),
});
const posts = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/posts" }),
  schema: ({ image }) =>
    z.object({
  uuid: z.string().uuid().optional(),
  title: z.string().optional(),
  excerpt: z.string().optional(),
  slug: z.string().optional(),
  date: z.string().optional(),
  published: z.boolean().default(true),
  featuredImage: image_with_altSchema(image).optional(),
  categories: z.array(z.string()).default([]),
  seo: seoSchema(image).optional(),
}),
});
const categories = defineCollection({
  loader: file("./src/content/categories.json", {
    parser: (text) => {
      const items = JSON.parse(text) as Array<Record<string, unknown>>;
      return items.map((item, i) => ({ id: String(i), ...item }));
    },
  }),
  schema: z.object({
  name: z.string().optional(),
  slug: z.string().optional(),
}),
});
const testimonials = defineCollection({
  loader: file("./src/content/testimonials.json", {
    parser: (text) => {
      const items = JSON.parse(text) as Array<Record<string, unknown>>;
      return items.map((item, i) => ({ id: String((item as any).uuid ?? i), ...item }));
    },
  }),
  schema: ({ image }) =>
    z.object({
  uuid: z.string().uuid().optional(),
  quote: z.string().optional(),
  author: z.string().optional(),
  role: z.string().optional(),
  logo: image().optional(),
  logoAlt: z.string().optional(),
}),
});
const redirects = defineCollection({
  loader: file("./src/content/redirects.json", {
    parser: (text) => {
      const items = JSON.parse(text) as Array<Record<string, unknown>>;
      return items.map((item, i) => ({ id: String(i), ...item }));
    },
  }),
  schema: z.object({
  from: z.string(),
  to: z.string(),
  status: z.enum(["301", "302"]).default("301"),
}),
});
const caseStudies = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/caseStudies" }),
  schema: ({ image }) =>
    z.object({
  uuid: z.string().uuid().optional(),
  title: z.string(),
  featuredImage: image_with_altSchema(image),
  excerpt: z.string().optional(),
  seo: seoSchema(image).optional(),
  gallery: image_with_altSchema(image).default([]),
}),
});

export const collections = { pages, posts, categories, testimonials, redirects, caseStudies };
